version: 2.1
jobs: 

  build:

    macos: 
      xcode: 12.4.0
    working_directory: /Users/distiller/project
    steps: 
      - checkout
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme Snapvideo -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4'
          environment:
            SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__
      - store_artifacts:
          path: /tmp/__SnapshotArtifacts__
      - store_test_results:
          path: test_output

